### ISSUE TITLE
Available module on forge is outdated

### ISSUE THREAD

**Issue by neomilium** [ccin2p3/puppet-syslog_ng#5]
Is there is a planned release of this module on puppet forge?

AFAICS, there was some plan to release 2.1.0 and now there are more features.

Thanks.

**Comment by faxm0dem** [comment]
Thanks for bringing that up!
I'll cook a release asap

**Comment by circulon** [comment]
Bump ...

Any chance this release can be updated on Puppet Forge?
or alternatively a release added here?

**Comment by faxm0dem** [comment]
I kind of started doing this some time ago and completely forgot about it.
Expect a new release by tomorrow !

**Comment by circulon** [comment]
Thanks
Much appreciated

**Comment by faxm0dem** [comment]
Done
